MYSQL_HOST: 127.0.0.1
MYSQL_PORT: 3306
MYSQL_USER: root
MYSQL_PWD: root
MYSQL_DB: hub_crayon

REDIST_HOST1: 127.0.0.1
#REDIST_HOST2: 192.168.110.243:7001
#REDIST_HOST3: 192.168.110.243:7002

spring:
  data:
    redis:
      host: ${REDIST_HOST1}
      port: 6379
      #      password: 123456
      database: 0
      timeout: 10000
  main:
    keep-alive: true
  threads:
    virtual:
      enabled: true
  datasource:
    druid:
      initial-size: 20
      max-active: 200
      min-idle: 20
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 600000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      keep-alive: true
      pool-prepared-statements: false
      stat-view-servlet:
        enabled: true
        allow: ""
        url-pattern: /druid/*
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 10000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8909
    openfeign:
      client:
        config:
          default:
            logger-level: full
      sentinel:
        enabled: true
      okhttp:
        enabled: true
      httpclient:
        enabled: false
        connection-timeout: 20000
      compression:
        request:
          enabled: true
        response:
          enabled: true

jetcache:
  statIntervalMinutes: 10
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: bean:tenantCacheKeyGenerator
      # 过期时间
      expireAfterWriteInMillis: 10000
      # 指定多长时间没有访问，就让缓存失效
      expireAfterAccessInMillis: 10000
      limit: 10000
  remote:
    default:
      type: redis.lettuce
      keyConvertor: bean:tenantCacheKeyGenerator
      broadcastChannel: fastjson2
      expireAfterWriteInMillis: 86400000
      mode: standalone
      uri: redis://${REDIST_HOST1}:6379
      #        - redis://${REDIST_HOST1}
      #        - redis://${REDIST_HOST2}
      #        - redis://${REDIST_HOST3}
      valueEncoder: kryo5
      valueDecoder: kryo5

# mybatis-plus 配置
mybatis-plus:
  tenant-enable: ture
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    capitalMode: true
    banner: false
    db-config:
      id-type: auto
      select-strategy: not_empty
      insert-strategy: not_empty
      update-strategy: not_null
  type-handlers-package: com.crayon.common.data.handler
  configuration:
    jdbc-type-for-null: 'null'
    call-setters-on-nulls: true
    shrink-whitespaces-in-sql: true

alarm:
  fund:
    url: https://open.larksuite.com
    path: /open-apis/bot/v2/hook/e880c6db-fcd1-4c2e-bc99-edb8723872e1
    open: 1
