spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PWD:root}
      url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DB:hub_crayon}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
# 报警地址
alarm:
  fund:
    url: https://open.larksuite.com
    path: /open-apis/bot/v2/hook/e880c6db-fcd1-4c2e-bc99-edb8723872e1
    open: 1

# 租户表维护
hy:
  tenant:
    column: tenant_id
    tables:
      - teacher
netty:
  client:
    service-name: netty-server-inner-websocket